version: 2
jobs:
  build-unlock:
    machine: true
    environment:
      DOCKER_REPOSITORY: unlockprotocol
    steps:
      - checkout
      - run:
          name: Build Unlock Image
          command: scripts/build-image.sh unlock
      - run:
          name: Publish Unlock Image
          command: scripts/push-image.sh unlock $CIRCLE_SHA1
  build-unlock-integration:
    machine: true
    environment:
      DOCKER_REPOSITORY: unlockprotocol
    steps:
      - checkout
      - run:
          name: Build Unlock Integration Image
          command: scripts/build-image.sh unlock-integration
      - run:
          name: Publish Unlock Integration Image
          command: scripts/push-image.sh unlock-integration $CIRCLE_SHA1
  unlock-app-tests:
    machine: true
    environment:
      DOCKER_REPOSITORY: unlockprotocol
    steps:
      - checkout
      - run:
          name: Pull Unlock Image
          command: scripts/pull-image.sh unlock "$CIRCLE_SHA1"
      - run:
          name: Creator Dashboard tests
          command: scripts/tests.sh unlock-app
  smart-contracts-tests:
    machine: true
    environment:
      DOCKER_REPOSITORY: unlockprotocol
    steps:
      - checkout
      - run:
          name: Pull Unlock Image
          command: scripts/pull-image.sh unlock "$CIRCLE_SHA1"
      - run:
          name: Smart Contract Tests
          command: scripts/tests.sh smart-contracts
  locksmith-tests:
    machine: true
    environment:
      DOCKER_REPOSITORY: unlockprotocol
      DB_USERNAME: locksmith_test
      DB_PASSWORD: password
      DB_NAME: locksmith_test
      DB_HOSTNAME: db
    steps:
      - checkout
      - run:
          name: Pull Unlock Image
          command: scripts/pull-image.sh unlock "$CIRCLE_SHA1"
      - run:
          name: Smart Contract Tests
          command: scripts/tests.sh locksmith
  paywall-tests:
    machine: true
    environment:
      DOCKER_REPOSITORY: unlockprotocol
    steps:
      - checkout
      - run:
          name: Pull Unlock Image
          command: scripts/pull-image.sh unlock "$CIRCLE_SHA1"
      - run:
          name: Smart Contract Tests
          command: scripts/tests.sh paywall
  integration-tests:
    machine: true
    environment:
      DOCKER_REPOSITORY: unlockprotocol
    steps:
      - checkout
      - run:
          name: Pull Unlock Image
          command: scripts/pull-image.sh unlock "$CIRCLE_SHA1"
      - run:
          name: Pull Unlock Integration Image
          command: scripts/pull-image.sh unlock-integration "$CIRCLE_SHA1"
      - run:
          name: Integration Tests
          command: scripts/integration-tests.sh
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-unlock
      - build-unlock-integration
      - unlock-app-tests:
          requires:
            - build-unlock
      - smart-contracts-tests:
          requires:
            - build-unlock
      - locksmith-tests:
          requires:
            - build-unlock
      - paywall-tests:
          requires:
            - build-unlock
      - integration-tests:
          requires:
            - build-unlock
            - build-unlock-integration
